version: 2.1

jobs:
  build-and-test:
    executor: yarn
    steps:
      - checkout
      - run:
          name: Install deps
          command: yarn install
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Lint code
          command: yarn lint

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test